export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_GIPHY_PENDING = 'REQUEST_GIPHY_PENDING';
export const REQUEST_GIPHY_SUCCESS = 'REQUEST_GIPHY_SUCCESS';
export const REQUEST_GIPHY_FAILED = 'REQUEST_GIPHY_FAILED';
